### ISSUE TITLE
As a developer, I want scenario one of the expand property working properly

### ISSUE THREAD

**Issue by shea-maykinmedia** [maykinmedia/open-personen#116]
Scenario: If the expand parameter is not included, relatives are not included
- [x] When an enrollee is consulted without an expand parameter
- [x] Then the attribute _embedded is not present in the response
- [x] And all attributes of the person are returned, if they have any value
- [x] And attribute _links.partners is returned
- [x] And attribute _links.parents is returned
- [x] And attribute _links.children is returned

Notes:
- for expand look at: rest_flex_fields
   - example in code: https://github.com/Haarlem/zaaktypecataloguscomponent/blob/master/src/ztc/api/utils/rest_flex_fields.py

**Comment by joeribekker** [comment]
I expect some generic solution for all these scenario's.

**Comment by shea-maykinmedia** [comment]
@joeribekker Yes, there will be.  I initially thought that having one ticket to cover all the scenarios would make the ticket too big but the more I think about it I think it should have just been one ticket.  However I can't seem to delete tickets so either I can:
- Keep them the way they are
- Move the other tickets to done and put all the scenarios into one of the already created tickets
- Put all the scenarios into one ticket and let you delete the other tickets 

Just let me know what you prefer
