### ISSUE TITLE
Fix date formats

### ISSUE THREAD

**Issue by shea-maykinmedia** [maykinmedia/open-personen#195]
Second point of https://github.com/maykinmedia/open-personen/issues/193

Dates should be formatted as YYYY-MM-DD rather than YYYYMMDD.

- [x] Fix dates

**Comment by shea-maykinmedia** [comment]
@joeribekker Just to double check, when a date is not returned from the BRP should Open Personen return `1900-01-01`?

**Comment by joeribekker** [comment]
> @joeribekker Just to double check, when a date is not returned from the BRP should Open Personen return `1900-01-01`?

No, just `null`.
