### ISSUE TITLE
As developer I want to compare my spec with the standard spec

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-personen#38]
so I know there are no breaking changes between these specifications.

Can use this tool for example: https://github.com/Azure/openapi-diff

And this tool can be run as a Travis task.

**Comment by shea-maykinmedia** [comment]
I think this is blocked by https://github.com/maykinmedia/open-personen/issues/9

Once the project is running in Travis then we'll be able to complete this issue.

**Comment by joeribekker** [comment]
@shea-maykinmedia Should be unblocked now :)

**Comment by shea-maykinmedia** [comment]
Yes, it should be now :)
