### ISSUE TITLE
As developer, I want to test retrieving 'ingeschreven personen' resources

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-personen#7]

**Comment by shea-maykinmedia** [comment]
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/tree/master/features

**Comment by joeribekker** [comment]
I'm dimissing this ticket. After discussing with Haal Centraal, the feature files are not really meant for automated testing at the moment. SoapUI and/or Postman tests are being developed and we'll integrate those in our CI once ready.
