### ISSUE TITLE
As user, I want to know how to create tokens to access the API

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-personen#76]
The way to create tokens should be described in the documentation, both via CLI and via the admin.

**Comment by shea-maykinmedia** [comment]
@joeribekker I was looking over the documentation here https://open-personen.readthedocs.io/en/latest/installation/authorizations.html and I think it already has everything needed for this ticket.

Should we consider this ticket closed or is there additional work you want done for this ticket?

**Comment by joeribekker** [comment]
Ah, good, it was done already.
